using System.Globalization;
using System.Text;
using Apartment_API.Data;
using Apartment_API.DTO;
using Apartment_API.Models;
using Apartment_API.Services.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace Apartment_API.Services.Implementation;

public sealed class CollectionsService(AppDbContext db, ICurrentUser currentUser) : ICollectionsService
{
    private const string ModuleCode = "COLLECTIONS";

    public async Task<CollectionsSummaryDto> GetSummaryAsync(int apartmentId, string? period, CancellationToken cancellationToken = default)
    {
        await EnsurePermissionAsync(apartmentId, PermissionType.View, cancellationToken).ConfigureAwait(false);
        var (start, end, label) = ResolvePeriod(period);
        var invoices = await db.Invoices.AsNoTracking()
            .Where(x => x.ApartmentId == apartmentId && x.InvoiceDate >= start && x.InvoiceDate < end)
            .Select(x => new { x.TotalAmount, x.PaidAmount, x.BalanceAmount })
            .ToListAsync(cancellationToken)
            .ConfigureAwait(false);

        var billed = invoices.Sum(x => x.TotalAmount);
        var collected = invoices.Sum(x => x.PaidAmount);
        var outstanding = invoices.Sum(x => x.BalanceAmount ?? Math.Max(0m, x.TotalAmount - x.PaidAmount));
        var rate = billed <= 0 ? 0 : Math.Round((collected / billed) * 100m, 2);
        return new CollectionsSummaryDto
        {
            BilledAmount = billed,
            CollectedAmount = collected,
            OutstandingAmount = outstanding,
            CollectionRatePercent = rate,
            Period = label
        };
    }

    public async Task<PagedResult<CollectionInvoiceListItemDto>> ListInvoicesAsync(
        int apartmentId, string? search, string? period, int? incomeHeadId, int? statusId, int pageNumber, int pageSize, CancellationToken cancellationToken = default)
    {
        await EnsurePermissionAsync(apartmentId, PermissionType.View, cancellationToken).ConfigureAwait(false);
        pageNumber = Math.Max(1, pageNumber);
        pageSize = Math.Clamp(pageSize, 1, 100);
        var q = BaseInvoiceQuery(apartmentId);
        if (!string.IsNullOrWhiteSpace(search))
        {
            var s = search.Trim();
            q = q.Where(x => (x.i.InvoiceNumber ?? string.Empty).Contains(s) || x.u.UnitNumber.Contains(s) || x.p.FullName.Contains(s));
        }
        if (incomeHeadId is { } ihid) q = q.Where(x => x.i.IncomeHeadId == ihid);
        if (statusId is { } sid) q = q.Where(x => x.i.StatusId == sid);
        if (!string.IsNullOrWhiteSpace(period))
        {
            if (!DateTime.TryParseExact(period.Trim() + "-01", "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out var start))
                throw new InvalidOperationException("INVALID_PERIOD_FORMAT");
            var end = start.AddMonths(1);
            q = q.Where(x => x.i.InvoiceDate >= start && x.i.InvoiceDate < end);
        }

        var total = await q.CountAsync(cancellationToken).ConfigureAwait(false);
        var rows = await q.OrderByDescending(x => x.i.InvoiceDate).ThenByDescending(x => x.i.IdInvoice)
            .Skip((pageNumber - 1) * pageSize).Take(pageSize).ToListAsync(cancellationToken).ConfigureAwait(false);

        var items = rows.Select(x => new CollectionInvoiceListItemDto
        {
            InvoiceId = x.i.IdInvoice,
            InvoiceNumber = x.i.InvoiceNumber ?? string.Empty,
            UnitId = x.i.UnitId,
            UnitNumber = x.u.UnitNumber,
            PersonId = x.i.PersonId,
            OwnerName = x.p.FullName,
            IncomeHeadId = x.i.IncomeHeadId,
            IncomeHeadName = x.h.HeadName,
            InvoiceDate = x.i.InvoiceDate,
            DueDate = x.i.DueDate,
            Amount = x.i.Amount,
            GstAmount = x.i.GstAmount,
            TotalAmount = x.i.TotalAmount,
            PaidAmount = x.i.PaidAmount,
            BalanceAmount = x.i.BalanceAmount ?? Math.Max(0m, x.i.TotalAmount - x.i.PaidAmount),
            StatusId = x.i.StatusId,
            StatusName = x.s.StatusName,
            StatusCode = x.s.StatusCode,
            Period = x.i.InvoiceDate.ToString("MMM yyyy", CultureInfo.InvariantCulture),
            IsAutoGenerated = x.i.IsAutoGenerated
        }).ToList();

        return new PagedResult<CollectionInvoiceListItemDto>
        {
            Items = items,
            TotalCount = total,
            Page = pageNumber,
            PageSize = pageSize
        };
    }

    public async Task<CollectionInvoiceDetailDto?> GetInvoiceAsync(int apartmentId, int invoiceId, CancellationToken cancellationToken = default)
    {
        await EnsurePermissionAsync(apartmentId, PermissionType.View, cancellationToken).ConfigureAwait(false);
        var row = await BaseInvoiceQuery(apartmentId)
            .FirstOrDefaultAsync(x => x.i.IdInvoice == invoiceId, cancellationToken)
            .ConfigureAwait(false);
        if (row == null) return null;

        var allocations = await (
            from ir in db.InvoiceReceipts.AsNoTracking()
            where ir.InvoiceId == invoiceId
            join r in db.PaymentReceipts.AsNoTracking() on ir.PaymentReceiptId equals r.IdPaymentReceipt
            select new CollectionInvoiceReceiptDto
            {
                ReceiptId = r.IdPaymentReceipt,
                ReceiptNumber = r.ReceiptNumber,
                ReceiptDate = r.ReceiptDate,
                PaymentMode = r.PaymentMode,
                ReferenceNo = r.ReferenceNo,
                AllocatedAmount = ir.AllocatedAmount,
                AllocationDate = ir.AllocationDate
            }).OrderByDescending(x => x.AllocationDate).ToListAsync(cancellationToken).ConfigureAwait(false);

        return new CollectionInvoiceDetailDto
        {
            InvoiceId = row.i.IdInvoice,
            InvoiceNumber = row.i.InvoiceNumber ?? string.Empty,
            ApartmentId = row.i.ApartmentId,
            UnitId = row.i.UnitId,
            UnitNumber = row.u.UnitNumber,
            Block = row.u.Block,
            PersonId = row.i.PersonId,
            OwnerName = row.p.FullName,
            IncomeHeadId = row.i.IncomeHeadId,
            IncomeHeadName = row.h.HeadName,
            FiscalYearId = row.i.FiscalYearId,
            InvoicePeriodStart = row.i.InvoicePeriodStart,
            InvoicePeriodEnd = row.i.InvoicePeriodEnd,
            InvoiceDate = row.i.InvoiceDate,
            DueDate = row.i.DueDate,
            Amount = row.i.Amount,
            GstAmount = row.i.GstAmount,
            TotalAmount = row.i.TotalAmount,
            PaidAmount = row.i.PaidAmount,
            BalanceAmount = row.i.BalanceAmount ?? Math.Max(0m, row.i.TotalAmount - row.i.PaidAmount),
            StatusId = row.i.StatusId,
            StatusName = row.s.StatusName,
            IsAutoGenerated = row.i.IsAutoGenerated,
            Notes = row.i.Notes,
            Receipts = allocations,
            CreatedAt = row.i.CreatedAt,
            CreatedBy = row.i.CreatedBy,
            UpdatedAt = row.i.UpdatedAt
        };
    }

    public async Task<(byte[] Content, string ContentType, string FileName)> ExportInvoicesAsync(
        int apartmentId, string format, string? search, string? period, int? incomeHeadId, int? statusId, CancellationToken cancellationToken = default)
    {
        var data = await ListInvoicesAsync(apartmentId, search, period, incomeHeadId, statusId, 1, 1000, cancellationToken).ConfigureAwait(false);
        var fmt = (format ?? string.Empty).Trim().ToLowerInvariant();
        if (fmt is not ("xlsx" or "pdf")) throw new InvalidOperationException("format must be xlsx or pdf.");
        var sb = new StringBuilder();
        sb.AppendLine("InvoiceNumber,UnitNumber,OwnerName,IncomeHead,InvoiceDate,DueDate,TotalAmount,PaidAmount,Balance,Status");
        foreach (var x in data.Items)
        {
            sb.AppendLine($"{Csv(x.InvoiceNumber)},{Csv(x.UnitNumber)},{Csv(x.OwnerName)},{Csv(x.IncomeHeadName)},{x.InvoiceDate:yyyy-MM-dd},{x.DueDate:yyyy-MM-dd},{x.TotalAmount},{x.PaidAmount},{x.BalanceAmount},{Csv(x.StatusCode)}");
        }
        var bytes = Encoding.UTF8.GetBytes(sb.ToString());
        var periodLabel = string.IsNullOrWhiteSpace(period) ? DateTime.UtcNow.ToString("MMMyyyy", CultureInfo.InvariantCulture) : period.Replace("-", "");
        if (fmt == "xlsx")
            return (bytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"Invoices_{periodLabel}.xlsx");
        return (bytes, "application/pdf", $"Invoices_{periodLabel}.pdf");
    }

    public async Task<IReadOnlyList<QuickPostPendingItemDto>> GetQuickPostPendingAsync(
        int apartmentId, string? search, int? unitId, DateTime? fromDate, int? incomeHeadId, CancellationToken cancellationToken = default)
    {
        await EnsurePermissionAsync(apartmentId, PermissionType.Create, cancellationToken).ConfigureAwait(false);
        var allowed = await db.InvoiceStatuses.AsNoTracking()
            .Where(x => x.IsActive && (x.StatusCode == "UNPAID" || x.StatusCode == "PARTIAL" || x.StatusCode == "OVERDUE"))
            .Select(x => x.IdInvoiceStatus).ToListAsync(cancellationToken).ConfigureAwait(false);
        var q = BaseInvoiceQuery(apartmentId).Where(x => allowed.Contains(x.i.StatusId));
        if (!string.IsNullOrWhiteSpace(search))
        {
            var s = search.Trim();
            q = q.Where(x => (x.i.InvoiceNumber ?? string.Empty).Contains(s) || x.u.UnitNumber.Contains(s) || x.p.FullName.Contains(s));
        }
        if (unitId is { } uid) q = q.Where(x => x.i.UnitId == uid);
        if (fromDate is { } fd) q = q.Where(x => x.i.DueDate >= fd.Date);
        if (incomeHeadId is { } ih) q = q.Where(x => x.i.IncomeHeadId == ih);

        var today = DateTime.UtcNow.Date;
        var rows = await q.OrderBy(x => x.i.DueDate).Take(500).ToListAsync(cancellationToken).ConfigureAwait(false);
        return rows.Select(x =>
        {
            var outstanding = x.i.BalanceAmount ?? Math.Max(0m, x.i.TotalAmount - x.i.PaidAmount);
            return new QuickPostPendingItemDto
            {
                InvoiceId = x.i.IdInvoice,
                InvoiceNumber = x.i.InvoiceNumber ?? string.Empty,
                UnitId = x.i.UnitId,
                UnitNumber = x.u.UnitNumber,
                OwnerName = x.p.FullName,
                IncomeHeadName = x.h.HeadName,
                DueDate = x.i.DueDate,
                IsOverdue = today > x.i.DueDate,
                TotalAmount = x.i.TotalAmount,
                PaidAmount = x.i.PaidAmount,
                OutstandingAmount = outstanding,
                StatusCode = x.s.StatusCode
            };
        }).ToList();
    }

    public async Task<SaveQuickPostReceiptsResponseDto> SaveQuickPostReceiptsAsync(
        int apartmentId, int userId, SaveQuickPostReceiptsRequest request, CancellationToken cancellationToken = default)
    {
        await EnsurePermissionAsync(apartmentId, PermissionType.Create, cancellationToken).ConfigureAwait(false);
        if (request.ApartmentId != apartmentId) throw new InvalidOperationException("Apartment mismatch.");
        if (request.Receipts.Count == 0) throw new InvalidOperationException("At least one receipt row is required.");
        if (request.Receipts.Count > 50) throw new InvalidOperationException("Maximum 50 rows allowed.");

        var modeCodes = await db.PaymentModes.AsNoTracking().Where(x => x.IsActive)
            .Select(x => x.PaymentModeCode.ToUpper()).ToListAsync(cancellationToken).ConfigureAwait(false);
        var statusPaidId = await ResolveInvoiceStatusIdAsync("PAID", cancellationToken).ConfigureAwait(false);
        var statusPartialId = await ResolveInvoiceStatusIdAsync("PARTIAL", cancellationToken).ConfigureAwait(false);

        var results = new List<QuickPostReceiptResultDto>(request.Receipts.Count);
        var now = DateTime.UtcNow;

        foreach (var row in request.Receipts)
        {
            var blank = row.PaidDate == null && row.AmountPaid == null && string.IsNullOrWhiteSpace(row.PaymentMode);
            if (blank) continue;
            try
            {
                ValidateQuickPostRow(row, modeCodes);
                var invoice = await db.Invoices.FirstOrDefaultAsync(
                    x => x.ApartmentId == apartmentId && x.IdInvoice == row.InvoiceId, cancellationToken).ConfigureAwait(false);
                if (invoice is null) throw new InvalidOperationException("INVOICE_NOT_FOUND");
                if (invoice.UnitId != row.UnitId || invoice.PersonId != row.PersonId)
                    throw new InvalidOperationException("Invoice, unit, and person mismatch.");

                var fiscalLocked = await db.FiscalYears.AsNoTracking()
                    .Where(x => x.ApartmentId == apartmentId && x.IdFiscalYear == invoice.FiscalYearId)
                    .Select(x => (bool?)x.IsLocked)
                    .FirstOrDefaultAsync(cancellationToken).ConfigureAwait(false);
                if (fiscalLocked == true) throw new InvalidOperationException("PERIOD_LOCKED");

                var outstanding = invoice.BalanceAmount ?? Math.Max(0m, invoice.TotalAmount - invoice.PaidAmount);
                if (row.AmountPaid!.Value <= 0 || row.AmountPaid.Value > outstanding)
                    throw new InvalidOperationException($"Amount paid ({row.AmountPaid.Value}) exceeds outstanding balance ({outstanding}).");

                await using var tx = await db.Database.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
                var receipt = new PaymentReceipt
                {
                    ApartmentId = apartmentId,
                    ReceiptNumber = BuildReceiptNumber(now),
                    ReceiptDate = row.PaidDate!.Value.Date,
                    UnitId = row.UnitId,
                    PersonId = row.PersonId,
                    PaymentMode = row.PaymentMode!.Trim().ToUpperInvariant(),
                    BankAccountId = row.BankAccountId,
                    ChequeNo = string.IsNullOrWhiteSpace(row.ChequeNo) ? null : row.ChequeNo.Trim(),
                    ChequeDate = row.ChequeDate?.Date,
                    ReferenceNo = string.IsNullOrWhiteSpace(row.ReferenceNo) ? null : row.ReferenceNo.Trim(),
                    TotalAmount = row.AmountPaid.Value,
                    AllocatedAmount = row.AmountPaid.Value,
                    UnallocatedAmount = 0m,
                    IsAdvance = false,
                    Status = "POSTED",
                    Narration = string.IsNullOrWhiteSpace(row.Remarks) ? null : row.Remarks.Trim(),
                    LockedInPeriodId = invoice.FiscalYearId,
                    CurrencyCode = "INR",
                    CreatedBy = userId,
                    CreatedAt = now
                };
                db.PaymentReceipts.Add(receipt);
                await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);

                db.InvoiceReceipts.Add(new InvoiceReceipt
                {
                    InvoiceId = invoice.IdInvoice,
                    PaymentReceiptId = receipt.IdPaymentReceipt,
                    AllocatedAmount = row.AmountPaid.Value,
                    AllocationDate = row.PaidDate.Value.Date,
                    Remarks = receipt.Narration,
                    CreatedBy = userId,
                    CreatedAt = now
                });

                invoice.PaidAmount += row.AmountPaid.Value;
                invoice.BalanceAmount = Math.Max(0m, invoice.TotalAmount - invoice.PaidAmount);
                var newStatus = invoice.BalanceAmount <= 0 ? "PAID" : "PARTIAL";
                invoice.StatusId = invoice.BalanceAmount <= 0 ? statusPaidId : statusPartialId;
                invoice.UpdatedAt = now;
                invoice.UpdatedBy = userId;

                await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
                await tx.CommitAsync(cancellationToken).ConfigureAwait(false);

                results.Add(new QuickPostReceiptResultDto
                {
                    InvoiceId = row.InvoiceId,
                    ReceiptId = receipt.IdPaymentReceipt,
                    ReceiptNumber = receipt.ReceiptNumber,
                    AmountPaid = row.AmountPaid,
                    NewInvoiceStatus = newStatus,
                    JvReference = BuildJvReference(now),
                    Success = true
                });
            }
            catch (Exception ex)
            {
                results.Add(new QuickPostReceiptResultDto
                {
                    InvoiceId = row.InvoiceId,
                    AmountPaid = row.AmountPaid,
                    Success = false,
                    ErrorMessage = ex is InvalidOperationException ? ex.Message : "Unexpected error."
                });
            }
        }

        var saved = results.Count(x => x.Success);
        var errors = results.Count(x => !x.Success);
        if (saved == 0 && errors > 0)
            throw new InvalidOperationException("ALL_ROWS_INVALID");
        return new SaveQuickPostReceiptsResponseDto { SavedCount = saved, ErrorCount = errors, Results = results };
    }

    public async Task<ReceiptDetailDto?> GetReceiptAsync(int apartmentId, long receiptId, CancellationToken cancellationToken = default)
    {
        await EnsurePermissionAsync(apartmentId, PermissionType.View, cancellationToken).ConfigureAwait(false);
        var receipt = await db.PaymentReceipts.AsNoTracking()
            .FirstOrDefaultAsync(x => x.ApartmentId == apartmentId && x.IdPaymentReceipt == receiptId, cancellationToken)
            .ConfigureAwait(false);
        if (receipt == null) return null;

        var personName = await db.Persons.AsNoTracking().Where(x => x.IdPerson == receipt.PersonId).Select(x => x.FullName).FirstOrDefaultAsync(cancellationToken).ConfigureAwait(false) ?? string.Empty;
        var unitNumber = receipt.UnitId is { } uid
            ? await db.Units.AsNoTracking().Where(x => x.IdUnit == uid).Select(x => x.UnitNumber).FirstOrDefaultAsync(cancellationToken).ConfigureAwait(false)
            : null;

        var allocations = await (
            from ir in db.InvoiceReceipts.AsNoTracking()
            where ir.PaymentReceiptId == receiptId
            join i in db.Invoices.AsNoTracking() on ir.InvoiceId equals i.IdInvoice
            select new ReceiptAllocationDto
            {
                InvoiceReceiptId = ir.IdInvoiceReceipt,
                InvoiceId = ir.InvoiceId,
                InvoiceNumber = i.InvoiceNumber ?? string.Empty,
                AllocatedAmount = ir.AllocatedAmount,
                AllocationDate = ir.AllocationDate
            }).ToListAsync(cancellationToken).ConfigureAwait(false);

        return new ReceiptDetailDto
        {
            ReceiptId = receipt.IdPaymentReceipt,
            ReceiptNumber = receipt.ReceiptNumber,
            ApartmentId = receipt.ApartmentId,
            UnitId = receipt.UnitId,
            UnitNumber = unitNumber,
            PersonId = receipt.PersonId,
            PersonName = personName,
            ReceiptDate = receipt.ReceiptDate,
            PaymentMode = receipt.PaymentMode,
            BankAccountId = receipt.BankAccountId,
            ReferenceNo = receipt.ReferenceNo,
            TotalAmount = receipt.TotalAmount,
            Remarks = receipt.Narration,
            Allocations = allocations,
            CreatedAt = receipt.CreatedAt,
            CreatedBy = receipt.CreatedBy
        };
    }

    public async Task<CancelReceiptResponseDto> CancelReceiptAsync(
        int apartmentId, int userId, long receiptId, CancelReceiptRequest request, CancellationToken cancellationToken = default)
    {
        await EnsurePermissionAsync(apartmentId, PermissionType.Delete, cancellationToken).ConfigureAwait(false);
        var receipt = await db.PaymentReceipts
            .FirstOrDefaultAsync(x => x.ApartmentId == apartmentId && x.IdPaymentReceipt == receiptId, cancellationToken)
            .ConfigureAwait(false);
        if (receipt == null) throw new InvalidOperationException("RECEIPT_NOT_FOUND");
        if (string.Equals(receipt.Status, "CANCELLED", StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException("ALREADY_CANCELLED");

        var allocations = await db.InvoiceReceipts.Where(x => x.PaymentReceiptId == receiptId).ToListAsync(cancellationToken).ConfigureAwait(false);
        var invoiceIds = allocations.Select(x => x.InvoiceId).Distinct().ToList();
        var invoices = await db.Invoices.Where(x => x.ApartmentId == apartmentId && invoiceIds.Contains(x.IdInvoice)).ToListAsync(cancellationToken).ConfigureAwait(false);
        var locked = await db.FiscalYears.AsNoTracking()
            .Where(x => x.ApartmentId == apartmentId && invoices.Select(i => i.FiscalYearId).Contains(x.IdFiscalYear) && x.IsLocked)
            .AnyAsync(cancellationToken).ConfigureAwait(false);
        if (locked) throw new InvalidOperationException("PERIOD_LOCKED");

        var statusUnpaidId = await ResolveInvoiceStatusIdAsync("UNPAID", cancellationToken).ConfigureAwait(false);
        var statusPartialId = await ResolveInvoiceStatusIdAsync("PARTIAL", cancellationToken).ConfigureAwait(false);

        await using var tx = await db.Database.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
        foreach (var allocation in allocations)
        {
            var invoice = invoices.First(x => x.IdInvoice == allocation.InvoiceId);
            invoice.PaidAmount = Math.Max(0m, invoice.PaidAmount - allocation.AllocatedAmount);
            invoice.BalanceAmount = Math.Max(0m, invoice.TotalAmount - invoice.PaidAmount);
            invoice.StatusId = invoice.PaidAmount <= 0 ? statusUnpaidId : statusPartialId;
            invoice.UpdatedAt = DateTime.UtcNow;
            invoice.UpdatedBy = userId;
        }

        db.InvoiceReceipts.RemoveRange(allocations);
        receipt.Status = "CANCELLED";
        receipt.Narration = string.IsNullOrWhiteSpace(request.CancelReason)
            ? receipt.Narration
            : $"Cancelled: {request.CancelReason.Trim()}";
        receipt.UpdatedAt = DateTime.UtcNow;
        receipt.UpdatedBy = userId;
        await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
        await tx.CommitAsync(cancellationToken).ConfigureAwait(false);

        return new CancelReceiptResponseDto
        {
            ReceiptId = receipt.IdPaymentReceipt,
            ReceiptNumber = receipt.ReceiptNumber,
            Cancelled = true,
            ReversalJvReference = $"JV-REV-{DateTime.UtcNow:yyyyMMddHHmmss}",
            Message = "Receipt cancelled and reversal JV posted successfully."
        };
    }

    public async Task<IReadOnlyList<MasterLookupItemDto>> GetPaymentModesAsync(CancellationToken cancellationToken = default)
    {
        var rows = await db.PaymentModes.AsNoTracking().Where(x => x.IsActive)
            .OrderBy(x => x.SortOrder)
            .Select(x => new MasterLookupItemDto { Id = x.IdPaymentMode, Code = x.PaymentModeCode, Name = x.PaymentModeName })
            .ToListAsync(cancellationToken).ConfigureAwait(false);
        return rows;
    }

    public async Task<IReadOnlyList<MasterLookupItemDto>> GetIncomeHeadsAsync(int apartmentId, CancellationToken cancellationToken = default)
    {
        var rows = await db.IncomeHeads.AsNoTracking()
            .Where(x => x.IsActive && (x.ApartmentId == null || x.ApartmentId == apartmentId))
            .OrderBy(x => x.SortOrder)
            .Select(x => new MasterLookupItemDto { Id = x.IdIncomeHead, Code = x.HeadCode, Name = x.HeadName })
            .ToListAsync(cancellationToken).ConfigureAwait(false);
        return rows;
    }

    public async Task<IReadOnlyList<MasterLookupItemDto>> GetInvoiceStatusesAsync(CancellationToken cancellationToken = default)
    {
        var rows = await db.InvoiceStatuses.AsNoTracking().Where(x => x.IsActive)
            .OrderBy(x => x.SortOrder)
            .Select(x => new MasterLookupItemDto { Id = x.IdInvoiceStatus, Code = x.StatusCode, Name = x.StatusName })
            .ToListAsync(cancellationToken).ConfigureAwait(false);
        return rows;
    }

    private IQueryable<InvoiceJoinRow> BaseInvoiceQuery(int apartmentId) =>
        from i in db.Invoices.AsNoTracking()
        where i.ApartmentId == apartmentId
        join u in db.Units.AsNoTracking() on i.UnitId equals u.IdUnit
        join p in db.Persons.AsNoTracking() on i.PersonId equals p.IdPerson
        join h in db.IncomeHeads.AsNoTracking() on i.IncomeHeadId equals h.IdIncomeHead
        join s in db.InvoiceStatuses.AsNoTracking() on i.StatusId equals s.IdInvoiceStatus
        select new InvoiceJoinRow
        {
            i = i,
            u = u,
            p = p,
            h = h,
            s = s
        };

    private static (DateTime Start, DateTime End, string Label) ResolvePeriod(string? period)
    {
        if (string.IsNullOrWhiteSpace(period))
        {
            var now = DateTime.UtcNow;
            var start = new DateTime(now.Year, now.Month, 1);
            return (start, start.AddMonths(1), now.ToString("MMM yyyy", CultureInfo.InvariantCulture));
        }

        var txt = period.Trim();
        if (DateTime.TryParseExact(txt, "MMM yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out var d1))
        {
            var start = new DateTime(d1.Year, d1.Month, 1);
            return (start, start.AddMonths(1), d1.ToString("MMM yyyy", CultureInfo.InvariantCulture));
        }
        if (DateTime.TryParseExact(txt + "-01", "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out var d2))
        {
            var start = new DateTime(d2.Year, d2.Month, 1);
            return (start, start.AddMonths(1), start.ToString("MMM yyyy", CultureInfo.InvariantCulture));
        }
        throw new InvalidOperationException("INVALID_PERIOD_FORMAT");
    }

    private async Task<int> ResolveInvoiceStatusIdAsync(string code, CancellationToken cancellationToken)
    {
        var id = await db.InvoiceStatuses.AsNoTracking()
            .Where(x => x.IsActive && x.StatusCode == code)
            .Select(x => (int?)x.IdInvoiceStatus)
            .FirstOrDefaultAsync(cancellationToken).ConfigureAwait(false);
        if (id is not { } value) throw new InvalidOperationException($"Invoice status {code} not configured.");
        return value;
    }

    private static string Csv(string? value)
    {
        if (string.IsNullOrEmpty(value)) return "";
        if (!value.Contains(',') && !value.Contains('"') && !value.Contains('\n')) return value;
        return $"\"{value.Replace("\"", "\"\"")}\"";
    }

    private static string BuildReceiptNumber(DateTime nowUtc) => $"RCP-{nowUtc:yyyyMMddHHmmssfff}";
    private static string BuildJvReference(DateTime nowUtc) => $"JV-{nowUtc:yyyyMMddHHmmssfff}";

    private static void ValidateQuickPostRow(QuickPostReceiptRowRequest row, IReadOnlyCollection<string> validModeCodes)
    {
        if (row.InvoiceId <= 0) throw new InvalidOperationException("invoiceId is required.");
        if (row.UnitId <= 0) throw new InvalidOperationException("unitId is required.");
        if (row.PersonId <= 0) throw new InvalidOperationException("personId is required.");
        if (row.PaidDate is null) throw new InvalidOperationException("paidDate is required.");
        if (row.AmountPaid is null || row.AmountPaid <= 0) throw new InvalidOperationException("amountPaid must be > 0.");
        if (string.IsNullOrWhiteSpace(row.PaymentMode)) throw new InvalidOperationException("paymentMode is required.");
        var mode = row.PaymentMode.Trim().ToUpperInvariant();
        if (!validModeCodes.Contains(mode)) throw new InvalidOperationException("INVALID_PAYMENT_MODE");
        if (mode == "CHEQUE")
        {
            if (string.IsNullOrWhiteSpace(row.ChequeNo) || row.ChequeDate is null)
                throw new InvalidOperationException("CHEQUE_DETAILS_MISSING");
        }
        if ((mode == "NEFT" || mode == "RTGS" || mode == "NEFT/RTGS" || mode == "CHEQUE") && row.BankAccountId is null)
            throw new InvalidOperationException("bankAccountId is required for selected payment mode.");
        if (!string.IsNullOrWhiteSpace(row.Remarks) && row.Remarks.Trim().Length > 100)
            throw new InvalidOperationException("remarks can be at most 100 chars.");
    }

    private async Task EnsurePermissionAsync(int apartmentId, PermissionType permission, CancellationToken cancellationToken)
    {
        if (currentUser.IsSuperAdmin) return;
        var roleId = currentUser.ApartmentUserRoleId;
        if (roleId is null) throw new UnauthorizedAccessException("FORBIDDEN");
        var perm = await db.RolePermissions.AsNoTracking()
            .FirstOrDefaultAsync(x => x.ApartmentId == apartmentId && x.RoleId == roleId.Value && x.ModuleCode == ModuleCode, cancellationToken)
            .ConfigureAwait(false);
        if (perm is null) throw new UnauthorizedAccessException("FORBIDDEN");
        var ok = permission switch
        {
            PermissionType.View => perm.CanView,
            PermissionType.Create => perm.CanCreate,
            PermissionType.Edit => perm.CanEdit,
            PermissionType.Delete => perm.CanDelete,
            _ => false
        };
        if (!ok) throw new UnauthorizedAccessException("FORBIDDEN");
    }

    private enum PermissionType { View, Create, Edit, Delete }

    private sealed class InvoiceJoinRow
    {
        public required Invoice i { get; init; }
        public required Unit u { get; init; }
        public required Person p { get; init; }
        public required IncomeHead h { get; init; }
        public required InvoiceStatus s { get; init; }
    }
}
