using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Apartment_API.Models;

[Table("Invoices", Schema = "dbo")]
public sealed class Invoice
{
    [Key, Column("IdInvoice")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdInvoice { get; set; }

    public int ApartmentId { get; set; }

    [Required, MaxLength(30)]
    [Column(TypeName = "varchar(30)")]
    public string Invoicer { get; set; } = string.Empty;

    [MaxLength(60)]
    public string? InvoiceSource { get; set; }

    public int UnitId { get; set; }
    public int PersonId { get; set; }
    public int IncomeHeadId { get; set; }
    public int FiscalYearId { get; set; }

    [Column(TypeName = "date")]
    public DateTime InvoicePeriodStart { get; set; }

    [Column(TypeName = "date")]
    public DateTime InvoicePeriodEnd { get; set; }

    [Column(TypeName = "date")]
    public DateTime InvoiceDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime DueDate { get; set; }

    [Precision(14, 2)]
    public decimal Amount { get; set; }

    [Precision(14, 2)]
    public decimal GstAmount { get; set; }

    [Precision(14, 2)]
    public decimal TotalAmount { get; set; }

    [Precision(14, 2)]
    public decimal PaidAmount { get; set; }

    [Precision(15, 2)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public decimal? BalanceAmount { get; set; }

    public int StatusId { get; set; }
    public bool IsAutoGenerated { get; set; }

    [MaxLength(500)]
    public string? Notes { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string? InvoiceNumber { get; set; }

    public DateTime CreatedAt { get; set; }
    public int CreatedBy { get; set; }
    public DateTime? UpdatedAt { get; set; }
    public int? UpdatedBy { get; set; }
}
