namespace Apartment_API.DTO;

public sealed class CollectionsSummaryDto
{
    public decimal BilledAmount { get; init; }
    public decimal CollectedAmount { get; init; }
    public decimal OutstandingAmount { get; init; }
    public decimal CollectionRatePercent { get; init; }
    public string Period { get; init; } = string.Empty;
}

public sealed class CollectionInvoiceListItemDto
{
    public int InvoiceId { get; init; }
    public string InvoiceNumber { get; init; } = string.Empty;
    public int UnitId { get; init; }
    public string UnitNumber { get; init; } = string.Empty;
    public int PersonId { get; init; }
    public string OwnerName { get; init; } = string.Empty;
    public int IncomeHeadId { get; init; }
    public string IncomeHeadName { get; init; } = string.Empty;
    public DateTime InvoiceDate { get; init; }
    public DateTime DueDate { get; init; }
    public decimal Amount { get; init; }
    public decimal GstAmount { get; init; }
    public decimal TotalAmount { get; init; }
    public decimal PaidAmount { get; init; }
    public decimal BalanceAmount { get; init; }
    public int StatusId { get; init; }
    public string StatusName { get; init; } = string.Empty;
    public string StatusCode { get; init; } = string.Empty;
    public string Period { get; init; } = string.Empty;
    public bool IsAutoGenerated { get; init; }
}

public sealed class CollectionInvoiceReceiptDto
{
    public long ReceiptId { get; init; }
    public string ReceiptNumber { get; init; } = string.Empty;
    public DateTime ReceiptDate { get; init; }
    public string PaymentMode { get; init; } = string.Empty;
    public string? ReferenceNo { get; init; }
    public decimal AllocatedAmount { get; init; }
    public DateTime AllocationDate { get; init; }
}

public sealed class CollectionInvoiceDetailDto
{
    public int InvoiceId { get; init; }
    public string InvoiceNumber { get; init; } = string.Empty;
    public int ApartmentId { get; init; }
    public int UnitId { get; init; }
    public string UnitNumber { get; init; } = string.Empty;
    public string? Block { get; init; }
    public int PersonId { get; init; }
    public string OwnerName { get; init; } = string.Empty;
    public int IncomeHeadId { get; init; }
    public string IncomeHeadName { get; init; } = string.Empty;
    public int FiscalYearId { get; init; }
    public DateTime InvoicePeriodStart { get; init; }
    public DateTime InvoicePeriodEnd { get; init; }
    public DateTime InvoiceDate { get; init; }
    public DateTime DueDate { get; init; }
    public decimal Amount { get; init; }
    public decimal GstAmount { get; init; }
    public decimal TotalAmount { get; init; }
    public decimal PaidAmount { get; init; }
    public decimal BalanceAmount { get; init; }
    public int StatusId { get; init; }
    public string StatusName { get; init; } = string.Empty;
    public bool IsAutoGenerated { get; init; }
    public string? Notes { get; init; }
    public IReadOnlyList<CollectionInvoiceReceiptDto> Receipts { get; init; } = [];
    public DateTime CreatedAt { get; init; }
    public int CreatedBy { get; init; }
    public DateTime? UpdatedAt { get; init; }
}

public sealed class QuickPostPendingItemDto
{
    public int InvoiceId { get; init; }
    public string InvoiceNumber { get; init; } = string.Empty;
    public int UnitId { get; init; }
    public string UnitNumber { get; init; } = string.Empty;
    public string OwnerName { get; init; } = string.Empty;
    public string IncomeHeadName { get; init; } = string.Empty;
    public DateTime DueDate { get; init; }
    public bool IsOverdue { get; init; }
    public decimal TotalAmount { get; init; }
    public decimal PaidAmount { get; init; }
    public decimal OutstandingAmount { get; init; }
    public string StatusCode { get; init; } = string.Empty;
}

public sealed class SaveQuickPostReceiptsRequest
{
    public int ApartmentId { get; set; }
    public int PostedByUserId { get; set; }
    public IReadOnlyList<QuickPostReceiptRowRequest> Receipts { get; set; } = [];
}

public sealed class QuickPostReceiptRowRequest
{
    public int InvoiceId { get; set; }
    public int UnitId { get; set; }
    public int PersonId { get; set; }
    public DateTime? PaidDate { get; set; }
    public decimal? AmountPaid { get; set; }
    public string? PaymentMode { get; set; }
    public int? BankAccountId { get; set; }
    public string? ChequeNo { get; set; }
    public DateTime? ChequeDate { get; set; }
    public string? ReferenceNo { get; set; }
    public string? Remarks { get; set; }
}

public sealed class QuickPostReceiptResultDto
{
    public int InvoiceId { get; init; }
    public long? ReceiptId { get; init; }
    public string? ReceiptNumber { get; init; }
    public decimal? AmountPaid { get; init; }
    public string? NewInvoiceStatus { get; init; }
    public string? JvReference { get; init; }
    public bool Success { get; init; }
    public string? ErrorMessage { get; init; }
}

public sealed class SaveQuickPostReceiptsResponseDto
{
    public int SavedCount { get; init; }
    public int ErrorCount { get; init; }
    public IReadOnlyList<QuickPostReceiptResultDto> Results { get; init; } = [];
}

public sealed class MasterLookupItemDto
{
    public int Id { get; init; }
    public string Code { get; init; } = string.Empty;
    public string Name { get; init; } = string.Empty;
}

public sealed class ReceiptAllocationDto
{
    public long InvoiceReceiptId { get; init; }
    public int InvoiceId { get; init; }
    public string InvoiceNumber { get; init; } = string.Empty;
    public decimal AllocatedAmount { get; init; }
    public DateTime AllocationDate { get; init; }
}

public sealed class ReceiptDetailDto
{
    public long ReceiptId { get; init; }
    public string ReceiptNumber { get; init; } = string.Empty;
    public int ApartmentId { get; init; }
    public int? UnitId { get; init; }
    public string? UnitNumber { get; init; }
    public int PersonId { get; init; }
    public string PersonName { get; init; } = string.Empty;
    public DateTime ReceiptDate { get; init; }
    public string PaymentMode { get; init; } = string.Empty;
    public int? BankAccountId { get; init; }
    public string? ReferenceNo { get; init; }
    public decimal TotalAmount { get; init; }
    public string? Remarks { get; init; }
    public IReadOnlyList<ReceiptAllocationDto> Allocations { get; init; } = [];
    public DateTime CreatedAt { get; init; }
    public int CreatedBy { get; init; }
}

public sealed class CancelReceiptRequest
{
    public string? CancelReason { get; set; }
}

public sealed class CancelReceiptResponseDto
{
    public long ReceiptId { get; init; }
    public string ReceiptNumber { get; init; } = string.Empty;
    public bool Cancelled { get; init; }
    public string ReversalJvReference { get; init; } = string.Empty;
    public string Message { get; init; } = string.Empty;
}
